### ISSUE TITLE
Station 354 point doesn't show on the map

### ISSUE THREAD

**Issue by ka7eh** [Oceans-1876/challenger-portal#47]
It's the last station.

**Comment by Rashmil-1999** [comment]
Not really a UI Issue.

**Comment by ka7eh** [comment]
I found the source of this bug. It's caused due to an issue in supercluster, one of maplibre's dependencies.

I've submitted a PR to that library, which is pending approval (https://github.com/mapbox/supercluster/pull/194).

When/if it gets merged, we need to check with maplibre maintainers to update supercluster to the new version, and then we can fix it here.

Meanwhile, we can use a different set of coordinates for the clustered stations, with their longitudes within the -180 and 180 degree range.

**Comment by Rashmil-1999** [comment]
You're right, we need to open a separate issue for this. For now, it is working on a local instance. We shall enable this in the next pr to see how it is when deployed.
